BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*.bbappend \
            ${LAYERDIR}/recipes-*/*.bb \
"

BBFILE_COLLECTIONS += "qti-automotive-distro"
BBFILE_PATTERN_qti-automotive-distro = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-automotive-distro = "18"
LAYERSERIES_COMPAT_qti-automotive-distro = "kirkstone scarthgap"
QTI_METAPATH_DISTRO := '${@os.path.normpath("${LAYERDIR}/")}'
