require conf/distro/include/auto-common.inc

DISTRO_NAME = "auto"
AUTOMOTIVE_PATH = "automotive"

#TODO: cleanup or rename qti-xxx DISTRO_FEATURES.
DISTRO_FEATURES:append = " \
    qti-adsp \
    qti-audio \
    qti-bluetooth \
    qti-fastcv \
    qti-audio-ar \
    qti-camera \
    qti-cdsp \
    qti-core \
    qti-data \
    qti-display \
    qti-extra \
    qti-graphics \
    qti-ml \
    qti-multimedia \
    qti-cv \
    qti-security \
    qti-tools \
    qti-vnw \
    qti-location \
    qti-avb \
    ab-boot-support \
    qti-wlan \
    qti-compute-platform \
    qti-rideware \
    qti-qcnode \
"

DISTRO_FEATURES:remove = "\
    qti-location \
    early-eth \
"

DISTRO_FEATURES:append:sa8797 = " \
    qti-audio-aw \
"

DISTRO_FEATURES:remove:sa8797 = " \
    qti-adsp \
    qti-audio \
    qti-audio-ar \
    qti-fastcv \
    qti-cdsp \
    qti-extra \
    qti-ml \
    qti-location \
"

DISTRO_FEATURES:remove:sa8797dc = " \
    qti-adsp \
    qti-audio \
    qti-bluetooth \
    qti-fastcv \
    qti-audio-ar \
    qti-camera \
    qti-cdsp \
    qti-data \
    qti-display \
    qti-extra \
    qti-graphics \
    qti-ml \
    qti-multimedia \
    qti-security \
    qti-tools \
    qti-vnw \
    qti-location \
    qti-avb \
    qti-wlan \
    ab-boot-support acl alsa bluetooth debuginfod ext2 pcmcia usbgadget usbhost nfs zeroconf pci 3g nfc vfat pam seccomp selinux \
"
