#This DISTRO conf use for factory test.

require conf/distro/auto.conf

DISTRO_NAME = "auto-fts"

DISTRO_FEATURES:append = " \
    qti-fts \
    fpga-test \
"
DISTRO_FEATURES:remove =" \
    selinux \
"

PRODUCT = "${MACHINE}-fts"

FACTORY_TEST = "1"

# Add fpga-test package to the root filesystem
IMAGE_INSTALL:append = " fpga-test"