#This DISTRO conf use for factory test.

require conf/distro/auto.conf

DISTRO_NAME = "auto-fts"

DISTRO_FEATURES:append = " \
    qti-fts \
"
DISTRO_FEATURES:remove =" \
    selinux \
"

# set sa8797-fts as default product in auto-fts distro
PRODUCT = "${BASEMACHINE}-fts"

FACTORY_TEST = "1"
