require conf/distro/include/auto-common.inc

DISTRO_NAME = "auto gvm headless"

PRODUCT = "${MACHINE}-headless"
PRODUCT:gvm-gen4-5 = "gvm-gen4-5-hl"
PRODUCT:quin-gvm-gen4-5 = "gvm-gen4-5-hl"

DEPLOY_NAME_BASE:gvm-gen4-5 = "${PRODUCT}"
DEPLOY_NAME_BASE:quin-gvm-gen4-5 = "${PRODUCT}"

DISTRO_FEATURES:remove = " wifi"

DISTRO_FEATURES:append = " \
    qti-core \
    qti-data \
    qti-extra \
    qti-graphics \
    qti-hypervisor \
    qti-security \
    qti-avb \
    qti-fde \
    qti-tools \
    ab-boot-support \
"

# Preferred refpolicy
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-targeted"
DEFAULT_ENFORCING = "enforcing"

DISTRO_FEATURES:remove:gvm-gen4-5 = " \
    qti-extra \
    qti-graphics \
    qti-bluetooth \
"

DISTRO_FEATURES:remove:quin-gvm-gen4-5 = " \
    qti-extra \
    qti-graphics \
    qti-bluetooth \
"
