require conf/distro/auto.conf

DISTRO_NAME = "sod"

DISTRO_FEATURES:remove = " \
    qti-avb \
    selinux \
"
MACHINE_FEATURES:remove = "\
    qti-bluetooth \
    qti-multimedia \
    qti-cv \
    qti-graphics \
    qti-audio-aw \
    qti-camera \
    qti-safety \
    qti-vnw \
    qti-security \
    qti-vmm \
    qti-compute-platform \
"

KERNEL_CMD_PARAMS = "rw rootwait nokaslr console=ttyMSM0,115200n8 earlycon=qcom_geni,0x884000 clk_ignore_unused kpti=0 cpuidle.off=1 loglevel=8 printk.devkmsg=on console_msg_format=syslog log_buf_len=256K qcom_scm.download_mode=1"

IMAGE_FEATURES:append = " debug-tweaks"

KERNEL_ARCH = "gen5auto"
